apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-kafka-client
  namespace: kafka # Deploying to the same namespace as Kafka for easier DNS resolution
  labels:
    app: dotnet-kafka-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-kafka-client
  template:
    metadata:
      labels:
        app: dotnet-kafka-client
    spec:
      containers:
      - name: producer-consumer
        image: hbacharya/devops-learn:latest # Update this!
        imagePullPolicy: Always
        env:
        # env are not in use now
        - name: Kafka__BootstrapServers
          value: "my-cluster-kafka-bootstrap:9092"
        - name: Kafka__Topic
          value: "test"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-kafka-client-svc
  namespace: kafka
spec:
  selector:
    app: dotnet-kafka-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80