apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-console
  namespace: kafka # Deploying to the same namespace as Kafka for easier DNS resolution
  labels:
    app: consumer-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-console
  template:
    metadata:
      labels:
        app: consumer-console
    spec:
      containers:
      - name: consumer-console
        image: ghcr.io/hbacharya/consumer-console:c8ec8b621273bab5f8bcd51bbde015978aa2c5ab---v1
        imagePullPolicy: Always
        env:
        # env are not in use now
        - name: Kafka__BootstrapServers
          value: "my-cluster-kafka-bootstrap:9092"
        - name: Kafka__SourceTopic
          value: "test-source"
        - name: Kafka__DestinationTopic
          value: "test-destination"
        - name: Kafka__GroupInstanceId
          value: "consumer-0"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
