apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: consumer-console
  namespace: kafka
spec:
  serviceName: consumer-console
  replicas: 2
  selector:
    matchLabels:
      app: consumer-console
  template:
    metadata:
      labels:
        app: consumer-console
    spec:
      containers:
      - name: consumer-console
        image: ghcr.io/hbacharya/consumer-console:c7df44a855b9a3b2f5352c3901b81a9913283867---v5
        imagePullPolicy: Always
        env:
        - name: Kafka__BootstrapServers
          value: "my-cluster-kafka-bootstrap:9092"
        - name: Kafka__SourceTopic
          value: "test-source"
        - name: Kafka__DestinationTopic
          value: "test-destination"
        - name: Kafka__GroupInstanceId
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
